Implement Typescript Support in Editor
NucleoidJS/IDE pull request #106
Opened 2023-06-27 17:18 UTC by durulkoca

2023-07-02 17:14 UTC, canmingir requested changes

2023-07-03 11:33 UTC, durulkoca commented on src/EventRegistry.js
> +      //  console.log("CONTEXT_CHANGED", vfs);
comment line removed

2023-07-03 11:34 UTC, durulkoca commented on src/sample.js
> +    ext: "ts",
all extensions will be ".ts" now.

2023-07-03 17:31 UTC, canmingir approved these changes

2023-07-06 08:42 UTC, merged