Dark Theme Integration
NucleoidJS/IDE pull request #122
Opened 2023-12-12 17:30 UTC by durulkoca

2023-12-12 17:31 UTC, halilcengel approved these changes

2023-12-26 12:56 UTC, canmingir requested changes

2023-12-26 12:56 UTC, canmingir commented on src/App.jsx
> +    "(prefers-color-scheme: dark)"
Can you reverse this to "light"?

2023-12-26 14:39 UTC, canmingir approved these changes

2023-12-26 16:40 UTC, merged